apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: backstage-chatgpt
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: backstage-chatgpt
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/Eknathreddy09/backstage-chatgptplugin
      ref:
        branch: main
